{{/*
PostgreSQL ServiceAccount
Dedicated service account for PostgreSQL with minimal permissions.
This follows security best practices by providing a separate identity
for the PostgreSQL component with no additional privileges.
*/}}
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inngest.postgresql.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "inngest.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  annotations:
    # Security: Explicitly document that this service account has no special permissions
    security.inngest.com/permissions: "minimal"
# No additional rules or permissions - PostgreSQL only needs basic pod execution
automountServiceAccountToken: false # Security: Disable token mounting for minimal attack surface
{{- end }}