{{/*
PostgreSQL Secret
Stores database credentials securely as base64-encoded values.
Only created when postgresql.enabled is true.

This secret contains:
- Individual credentials (username, password, database)  
- Complete connection URI for easy consumption by applications

Security: Database passwords are stored in Secrets instead of ConfigMaps
to prevent exposure in logs or kubectl describe output.
*/}}
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inngest.postgresql.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "inngest.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  # Individual database credentials (base64 encoded)
  postgres-password: {{ .Values.postgresql.auth.password | b64enc }}
  postgres-username: {{ .Values.postgresql.auth.username | b64enc }}
  postgres-database: {{ .Values.postgresql.auth.database | b64enc }}
  # Complete connection URI for applications (base64 encoded)
  postgres-uri: {{ printf "postgres://%s:%s@%s:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "inngest.postgresql.fullname" .) .Values.postgresql.auth.database | b64enc }}
{{- end }}