{{/*
Redis ServiceAccount
Dedicated service account for Redis with minimal permissions.
This follows security best practices by providing a separate identity
for the Redis component with no additional privileges.
*/}}
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inngest.redis.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "inngest.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  annotations:
    # Security: Explicitly document that this service account has no special permissions
    security.inngest.com/permissions: "minimal"
# No additional rules or permissions - Redis only needs basic pod execution
automountServiceAccountToken: false # Security: Disable token mounting for minimal attack surface
{{- end }}