{{/*
Inngest Secret
Kubernetes Secret containing sensitive Inngest authentication keys.

This Secret stores:
- INNGEST_EVENT_KEY: Used by applications to send events to Inngest
- INNGEST_SIGNING_KEY: Used to sign and validate data between server and apps

These keys are base64-encoded and securely stored in Kubernetes etcd.
Ensure these values are set in your values.yaml or via --set flags.

Security: Never commit these keys to version control or expose them in logs.
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inngest.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "inngest.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.inngest.eventKey }}
  # Event key for applications to send events to Inngest
  INNGEST_EVENT_KEY: {{ .Values.inngest.eventKey | b64enc }}
  {{- end }}
  {{- if .Values.inngest.signingKey }}
  # Signing key for request validation and KEDA metrics authentication
  INNGEST_SIGNING_KEY: {{ .Values.inngest.signingKey | b64enc }}
  {{- end }}