{{/*
Inngest Service Account
Kubernetes ServiceAccount for Inngest pods.
Only created when serviceAccount.create is true.

This ServiceAccount provides:
- Identity for Inngest pods in the cluster
- Foundation for RBAC permissions (if needed)
- Support for annotations like IAM role bindings (AWS, GCP, Azure)

The ServiceAccount can be customized with annotations for cloud provider
integrations, such as workload identity or IAM roles for service accounts.
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inngest.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "inngest.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  # Custom annotations (e.g., for cloud provider IAM role bindings)
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}